### ISSUE TITLE
Handling Invalid or Unknown Case IDs in Test Run

### ISSUE THREAD

**Issue by Booklynn** [gurock/trcli#148]
### What would you like the TestRail CLI to be able to do?

Enable skipping unknown or invalid test cases not belonging to the specified test run, instead of aborting the command execution. This enhancement will improve usability and flexibility when managing test results using the CLI.

### Why is this feature necessary on the TestRail CLI?

The feature is necessary on the TestRail CLI to enable efficient handling of multiple test case results. It allows automation testers to upload valid test cases while skipping any unknown or invalid ones. This ensures a streamlined test management process and eliminates interruptions caused by incompatible or irrelevant data.

### More details

I have already coded and opened PR https://github.com/gurock/trcli/pull/147

### Interested in implementing it yourself?

Yes

**Comment by Booklynn** [comment]
@piotroxp Unfornatately, they have not reviewed my pull request.

**Comment by Testinator-X** [comment]
@d-rede will this ever be merged?

**Comment by d-rede** [comment]
Hello @Booklynn 

Firstly let me praise you for your effort to make the trcli work for your use cases and thank you for opening this issue.

@Testinator-X thanks for bringing this to my attention.

The straight answer to whether the PR will merged is no, but let me explain why. There are two different features being implemented in the PR:

1. **Ability to add new cases when updating runs**
This is something we have been thinking of implementing for a while and we will support it starting from our next release

2. **Ignoring inexistent TestRail case IDs in reports**
Unfortunately we do not intend to support this behavior because we see it as counterproductive, potentially leading to more trouble than benefit by allowing people to have erroneous IDs in their reports. No report should have an ID if that ID does not exist, that is our stance.

Nonetheless we appreciate this kind of contribution, this is the kind of thing that pushes us to make the CLI better.


Regards
