### ISSUE TITLE
Test plan name for test runs

### ISSUE THREAD

**Issue by AlbertoValdivia20** [gurock/trcli#206]
### What would you like the TestRail CLI to be able to do?

Hello, I would like to ask if trcli will have in the future a way to add test runs to an specific test plan passing the name of the test plan, right now I only see a way to do it with the id.

### Why is this feature necessary on the TestRail CLI?

This is very useful for grouping the nightly regressions by month into a test plan.
As it is right now I would need each month to create a new test plan and modify the pipeline.

### Interested in implementing it yourself?

No

**Comment by Testinator-X** [comment]
The name of the plan is not necessarily unique. There can be several active plans with the same name at the same time. How do you suggest that the CLI tool itself should decide to which plan the run should be assigned if several plans with the same name exist at the same time (intentionally or unintentionally)? 

In my opinion, it makes much more sense for your use case if your pipeline creates the new plan via API. You will then receive the ID as a response and you should remember this in your pipeline in order to add plans to this run in the future. 🤔

At least that's how we do it. When we deploy a new version of our application, a milestone with the version number and a run with the name of the milestone are automatically created and the results are then added to this run via CLI Tool.

**Comment by AlbertoValdivia20** [comment]
I was think in managing like suite for example that you can use the option you want
From the Readme:
  --suite-id          Suite ID to submit results to.  [x>=1]
  --suite-name        Suite name to submit results to.

Because what I want is to use the same test plan for a whole month and create a new one for each month.
As you say to deploy a new version it's easy to do it the way everything is right now.
I'm also taking into account that the way we create testplans in our team it's almost impossible for us to duplicate testplans.

**Comment by AlbertoValdivia20** [comment]
The idea would be, I have in the pipeline this test plan name AUTO_REGRESSION_${ENV}_${monthAndYear}
If it already exists add the test run, if not create a new test plan with that name
